const GroupA = [
    {
        place: 1,
        src: "/images/netherlands.png",
        name: "Netherlands",
        GK: ["Remko Pasveer","Justin Bijlow","Andries Noppert"],
        DF: ["Jurriën Timber","Matthijs de Ligt","Virgil van Dijk","Nathan Aké","Stefan de Vrij","Tyrell Malacia","Daley Blind","Denzel Dumfries","Jeremie Frimpong"],
        MF: ["Steven Berghuis","Davy Klaassen","Marten de Roon","Teun Koopmeiners","Frenkie de Jong","Kenneth Taylor","Xavi Simons"],
        FW: ["Steven Bergwijn","Cody Gakpo","Luuk de Jong","Memphis Depay","Noa Lang","Vincent Janssen","Wout Weghorst"],
        W: 2,
        R: 1,
        P: 0,
        BZ: 5,
        BS: 1,
        RB: 4,
        Pkt: 7,
    },
    {
        place: 2,
        src: "/images/senegal.png",
        name: "Senegal",
        GK: ["Seny Dieng","Édouard Mendy","Alfred Gomis"],
        DF: ["Formose Mendy","Kalidou Koulibaly","Pape Abou Cissé","Moussa N'Diaye","Fodé Ballo-Touré","Ismail Jakobs","Youssouf Sabaly","Abdou Diallo"],
        MF: ["Idrissa Gueye","Nampalys Mendy","Cheikhou Kouyaté","Pathé Ciss","Krépin Diatta","Pape Matar Sarr","	Moustapha Name","Mamadou Loum","Pape Gueye"],
        FW: ["Nicolas Jackson","Boulaye Dia","Iliman Ndiaye","Ismaïla Sarr","Famara Diédhiou","Bamba Dieng"],
        W: 2,
        R: 0,
        P: 1,
        BZ: 5,
        BS: 4,
        RB: 1,
        Pkt: 6,
        
    },
    {
        place: 3,
        src: "/images/ecuador.png",
        name: "Ecuador",
        GK: ["Hernán Galíndez","Moisés Ramírez","Alexander Domínguez"],
        DF: ["Félix Torres","Piero Hincapié","Robert Arboleda","William Pacho","Pervis Estupiñán","	Xavier Arreaga","Ángelo Preciado","Diego Palacios","Jackson Porozo"],
        MF: ["José Cifuentes","	Carlos Gruezo","Ángel Mena","Jeremy Sarmiento","Gonzalo Plata","Jhegson Méndez","Alan Franco","Moisés Caicedo"],
        FW: ["Ayrton Preciado","Romario Ibarra","Michael Estrada","Enner Valencia","Djorkaeff Reasco","Kevin Rodríguez"],
        W: 1,
        R: 1,
        P: 1,
        BZ: 4,
        BS: 3,
        RB: 1,
        Pkt: 4,
        
    },
    {
        place: 4,
        src: "/images/qatar.png",
        name: "Qatar",
        GK: ["Meshaal Barsham","Mahmud Abunada","Yousef Baliadeh","Shehab Ellethy"],
        DF: ["Ismaeel Mohammad","Tarek Salman","Homam Ahmed","Mohammed Waad","Mohammed Aiash","Jassem Gaber","Diyab Taha"],
        MF: ["Ali Assadalla","Assim Madibo","Salem Al-Hajri","Abdelrahman Moustafa","Hashim Ali","Mostafa Meshaal","Hazem Shehata","Tameem Al-Abdullah","Abdulla Al-Yazidi","Faisal Azadi","Ahmed Fadhel"],
        FW: ["Mohammed Muntari","Yusuf Abdurisag","Khalid Muneer","Naif Al-Hadhrami","Amro Surag"],
        W: 0,
        R: 0,
        P: 3,
        BZ: 1,
        BS: 7,
        RB: -6,
        Pkt: 0,
        
    },
]
const GroupB = [
    {
        place: 1,
        src: "/images/england.png",
        name: "England",
        GK: ["Jordan Pickford","Nick Pope","Aaron Ramsdale"],
        DF: ["Kyle Walker","Luke Shaw","John Stones","Harry Maguire","Kieran Trippier","Eric Dier","Conor Coady","Trent Alexander-Arnold"],
        MF: ["Declan Rice","Jordan Henderson","	Kalvin Phillips","Mason Mount","Jude Bellingham","Conor Gallagher"],
        FW: ["Jack Grealish","Harry Kane","Raheem Sterling","Marcus Rashford","Bukayo Saka","Phil Foden","Callum Wilson","James Maddison",],
        W: 2,
        R: 1,
        P: 0,
        BZ: 9,
        BS: 2,
        RB: 7,
        Pkt: 7,
    },
    {
        place: 2,
        src: "/images/usa.png",
        name: "USA",
        GK: ["Matt Turner","	Ethan Horvath","	Sean Johnson"],
        DF: ["	Sergiño Dest","	Walker Zimmerman","Antonee Robinson","	Tim Ream","Aaron Long","	Shaq Moore","	Cameron Carter-Vickers","	DeAndre Yedlin","Joe Scally"],
        MF: ["	Tyler Adams","Yunus Musah","Weston McKennie","	Brenden Aaronson","	Luca de la Torre","	Cristian Roldan","	Kellyn Acosta"],
        FW: ["	Giovanni Reyna","Jesús Ferreira","Christian Pulisic","Jordan Morris","Haji Wright","Timothy Weah","	Josh Sargent"],
        W: 1,
        R: 2,
        P: 0,
        BZ: 2,
        BS: 1,
        RB: 1,
        Pkt: 5,
    },
    {
        place: 3,
        src: "/images/iran.png",
        name: "Iran",
        GK: ["Alireza Beiranvand","Payam Niazmand","Amir Abedzadeh","Hossein Hosseini"],
        DF: ["Sadegh Moharrami","Ehsan Hajsafi","Shojae Khalilzadeh","Milad Mohammadi","Morteza Pouraliganji","	Hossein Kanaanizadegan","Rouzbeh Cheshmi","Majid Hosseini","Ramin Rezaeian","Abolfazl Jalali"],
        MF: ["Saeid Ezatolahi","Alireza Jahanbakhsh","Vahid Amiri","Saman Ghoddos","Mehdi Torabi","	Ali Gholizadeh","Ali Karimi","	Ahmad Nourollahi"],
        FW: ["Mehdi Taremi","Karim Ansarifard","Sardar Azmoun"],
        W: 1,
        R: 0,
        P: 2,
        BZ: 4,
        BS: 7,
        RB: -3,
        Pkt: 3,
    },
    {
        place: 4,
        src: "/images/wales.png",
        name: "Wales",
        GK: ["	Wayne Hennessey","	Danny Ward","	Adam Davies"],
        DF: ["	Chris Gunter","	Neco Williams","	Ben Davies","Chris Mepham","Joe Rodon","	Connor Roberts","	Ethan Ampadu","	Tom Lockyer","	Ben Cabango"],
        MF: ["	Joe Allen","	Harry Wilson","Aaron Ramsey","Joe Morrell","	Jonny Williams","	Sorba Thomas","Dylan Levitt","	Rubin Colwill","	Matthew Smith"],
        FW: ["Brennan Johnson","Gareth Bale","	Kieffer Moore","Mark Harris","	Daniel James"],
        W: 0,
        R: 1,
        P: 2,
        BZ: 1,
        BS: 6,
        RB: -5,
        Pkt: 1,
    },
]
const GroupC = [
    {
        place: 1,
        src: "/images/argentina.png",
        name: "Argentina",
        GK: ["Franco Armani","Gerónimo Rulli","Emiliano Martínez"],
        DF: ["Juan Foyth","Nicolás Tagliafico","Gonzalo Montiel","Germán Pezzella","Marcos Acuña","Cristian Romero","Nicolás Otamendi","Lisandro Martínez","Nahuel Molina"],
        MF: ["Leandro Paredes","Rodrigo De Paul","Exequiel Palacios","Thiago Almada","Alejandro Gómez","Guido Rodríguez","Alexis Mac Allister","Enzo Fernández"],
        FW: ["Julián Álvarez","Lionel Messi","Ángel Di María","Ángel Correa","Paulo Dybala","Lautaro Martínez"],
        W: 2,
        R: 0,
        P: 1,
        BZ: 5,
        BS: 2,
        RB: 3,
        Pkt: 6,
    },
    {
        place: 2,
        src: "/images/poland.png",
        name: "Poland",
        GK: ["Wojciech Szczęsny","Łukasz Skorupski","Kamil Grabara"],
        DF: ["Matty Cash","Artur Jędrzejczyk","Mateusz Wieteska","Jan Bednarek","Jakub Kiwior","Kamil Glik ","Bartosz Bereszyński","Nicola Zalewski","Robert Gumny"],
        MF: ["Krystian Bielik","Damian Szymański","	Grzegorz Krychowiak","Kamil Grosicki","Jakub Kamiński","Szymon Żurkowski","Sebastian Szymański","Piotr Zieliński","Przemysław Frankowski","Michał Skóraś"],
        FW: ["Arkadiusz Milik","Robert Lewandowski","Karol Świderski","	Krzysztof Piątek"],
        W: 1,
        R: 1,
        P: 1,
        BZ: 2,
        BS: 2,
        RB: 0,
        Pkt: 4,
    },
    {
        place: 3,
        src: "/images/mexico.png",
        name: "Mexico",
        GK: ["	Alfredo Talavera","	Rodolfo Cota","	Guillermo Ochoa"],
        DF: ["	Néstor Araujo","	César Montes","Johan Vásquez","Gerardo Arteaga","Héctor Moreno","	Jorge Sánchez","Jesús Gallardo","Kevin Álvarez"],
        MF: ["Edson Álvarez","	Luis Romo","Carlos Rodríguez","Érick Gutiérrez","Héctor Herrera","	Orbelín Pineda","Andrés Guardado","Uriel Antuna","Luis Chávez","	Roberto Alvarado"],
        FW: ["Raúl Jiménez","	Alexis Vega","	Rogelio Funes Mori","	Henry Martín","	Hirving Lozano"],
        W: 1,
        R: 1,
        P: 1,
        BZ: 2,
        BS: 3,
        RB: -1,
        Pkt: 4,
    },
    {
        place: 4,
        src: "/images/saudi-arabia.png",
        name: "Saudi_Arabia",
        GK: ["Mohammed Al-Rubaie","Mohammed Al-Owais","	Nawaf Al-Aqidi",],
        DF: ["	Sultan Al-Ghannam","Abdullah Madu","	Abdulelah Al-Amri","Ali Al-Bulaihi","Mohammed Al-Breik","Saud Abdulhamid","Yasser Al-Shahrani","Hassan Tambakti",],
        MF: ["	Salman Al-Faraj","Abdulellah Al-Malki","Salem Al-Dawsari","Abdullah Otayf","	Ali Al-Hassan","Sami Al-Najei","	Nawaf Al-Abed","Hattan Bahebri","Abdulrahman Al-Aboud","Mohamed Kanno","	Nasser Al-Dawsari","Riyadh Sharahili",],
        FW: ["Firas Al-Buraikan","Saleh Al-Shehri","Haitham Asiri",],
        W: 1,
        R: 0,
        P: 2,
        BZ: 3,
        BS: 5,
        RB: -2,
        Pkt: 3,
    },
]
const GroupD = [
    {
        place: 1,
        src: "/images/france.png",
        name: "France",
        GK: ["Hugo Lloris","Steve Mandanda","Alphonse Areola"],
        DF: ["Benjamin Pavard","Axel Disasi","Raphaël Varane","Jules Koundé","William Saliba","	Dayot Upamecano","Lucas Hernandez","Théo Hernandez","	Ibrahima Konaté"],
        MF: ["Matteo Guendouzi","Aurélien Tchouaméni","Youssouf Fofana","Adrien Rabiot","Jordan Veretout","Eduardo Camavinga"],
        FW: ["Antoine Griezmann","Olivier Giroud","Kylian Mbappé","	Ousmane Dembélé","	Randal Kolo Muani","Kingsley Coman","Marcus Thuram"],
        W: 2,
        R: 0,
        P: 1,
        BZ: 6,
        BS: 3,
        RB: 3,
        Pkt: 6,
    },
    {
        place: 2,
        src: "/images/Australia.png",
        name: "Australia",
        GK: ["Mathew Ryan","	Andrew Redmayne","	Danny Vukovic"],
        DF: ["	Miloš Degenek","	Nathaniel Atkinson","	Kye Rowles","	Fran Karačić","	Bailey Wright","	Aziz Behich","	Harry Souttar","	Thomas Deng","Joel King"],
        MF: ["Ajdin Hrustic","	Aaron Mooy","	Riley McGree","	Cameron Devlin","	Jackson Irvine","Keanu Baccus",],
        FW: ["Marco Tilio","Mathew Leckie","Jamie Maclaren","	Awer Mabil","Mitchell Duke","	Garang Kuol","Craig Goodwin","	Jason Cummings",],
        W: 2,
        R: 0,
        P: 1,
        BZ: 3,
        BS: 4,
        RB: -1,
        Pkt: 6,
    },
    {
        place: 3,
        src: "/images/tunisia.png",
        name: "Tunisia",
        GK: ["	Aymen Mathlouthi","Aymen Dahmen","	Bechir Ben Saïd","Mouez Hassen",],
        DF: ["	Bilel Ifa","	Montassar Talbi","	Yassine Meriah","	Nader Ghandri","Dylan Bronn","Ali Maâloul","	Mohamed Dräger","	Wajdi Kechrida","	Ali Abdi",],
        MF: ["Hannibal Mejbri","Ferjani Sassi","Aïssa Laïdouni","Mohamed Ali Ben Romdhane","	Ellyes Skhiri","	Ghailene Chaalali","Anis Ben Slimane",],
        FW: ["Youssef Msakni","Issam Jebali","Wahbi Khazri","	Taha Yassine Khenissi","	Seifeddine Jaziri","Naïm Sliti",],
        W: 1,
        R: 1,
        P: 1,
        BZ: 1,
        BS: 1,
        RB: 0,
        Pkt: 4,
    },
    {
        place: 4,
        src: "/images/denmark.png",
        name: "Denmark",
        GK: ["Kasper Schmeichel","Oliver Christensen","	Frederik Rønnow",],
        DF: ["Joachim Andersen","	Victor Nelsson","Simon Kjær","Joakim Mæhle","Rasmus Kristensen","	Jens Stryger Larsen","Daniel Wass","	Alexander Bah",],
        MF: ["Mathias Jensen","	Thomas Delaney","	Christian Eriksen","Christian Nørgaard","Pierre-Emile Højbjerg","Robert Skov","Jesper Lindstrøm",],
        FW: ["Martin Braithwaite","	Andreas Skov Olsen","Kasper Dolberg","Mikkel Damsgaard","	Jonas Wind","Yussuf Poulsen","	Andreas Cornelius",],
        W: 0,
        R: 1,
        P: 2,
        BZ: 1,
        BS: 3,
        RB: -2,
        Pkt: 1,
    },
]
const GroupE = [
    {
        place: 1,
        src: "/images/japan.png",
        name: "Japan",
        GK: ["Eiji Kawashima","Shūichi Gonda","Daniel Schmidt",],
        DF: ["	Miki Yamane","Shogo Taniguchi","	Ko Itakura","	Yuto Nagatomo","	Takehiro Tomiyasu","","Hiroki Sakai","	Maya Yoshida","Hiroki Ito",],
        MF: ["Wataru Endo","Gaku Shibasaki","	Ritsu Dōan","Kaoru Mitoma","Takumi Minamino","Takefusa Kubo","Hidemasa Morita","Junya Ito","	Daichi Kamada","Ao Tanaka","Yuki Soma",],
        FW: ["Takuma Asano","Shuto Machino","	Ayase Ueda","	Daizen Maeda",],
        W: 2,
        R: 0,
        P: 1,
        BZ: 4,
        BS: 3,
        RB: 1,
        Pkt: 6,
    },
    {
        place: 2,
        src: "/images/spain.png",
        name: "Spain",
        GK: ["Robert Sánchez","	David Raya","	Unai Simón",],
        DF: ["César Azpilicueta","Eric García","	Pau Torres","Alejandro Balde","	Hugo Guillamón","Jordi Alba","Dani Carvajal","	Aymeric Laporte",],
        MF: ["Marcos Llorente","	Koke","Gavi","Rodri","Carlos Soler","Pedri",],
        FW: ["Álvaro Morata","Marco Asensio","Ferran Torres","Nico Williams","Yeremy Pino","Dani Olmo","	Pablo Sarabia","Ansu Fati",],
        W: 1,
        R: 1,
        P: 1,
        BZ: 9,
        BS: 3,
        RB: 6,
        Pkt: 4,
    },
    {
        place: 3,
        src: "/images/germany.png",
        name: "Germany",
        GK: ["Manuel Neuer","Kevin Trapp","Marc-André ter Stegen",],
        DF: ["	Antonio Rüdiger","	David Raum","	Matthias Ginter","Thilo Kehrer","Niklas Süle","Lukas Klostermann","	Christian Günter","	Nico Schlotterbeck","Armel Bella-Kotchap",],
        MF: ["Joshua Kimmich","Kai Havertz","Leon Goretzka","Mario Götze","	Jamal Musiala","	Julian Brandt","Jonas Hofmann","İlkay Gündoğan",],
        FW: ["Niclas Füllkrug","	Serge Gnabry","Thomas Müller","Leroy Sané","Karim Adeyemi","	Youssoufa Moukoko",],
        W: 1,
        R: 1,
        P: 1,
        BZ: 6,
        BS: 5,
        RB: 1,
        Pkt: 4,
    },
    {
        place: 4,
        src: "/images/costa-rica.png",
        name: "Costa_ricka",
        GK: ["Keylor Navas","Esteban Alvarado","Patrick Sequeira",],
        DF: ["Juan Pablo Vargas","Keysher Fuller","	Óscar Duarte","Bryan Oviedo","Francisco Calvo","Carlos Martínez","Kendall Waston","Rónald Matarrita",],
        MF: ["Daniel Chacón","	Celso Borges","Jewison Bennette","Bryan Ruiz","	Gerson Torres","Youstin Salas","Yeltsin Tejeda","Brandon Aguilera","Douglas López","Roan Wilson","	Anthony Hernández","Álvaro Zamora",],
        FW: ["	Anthony Contreras","Johan Venegas","Joel Campbell",],
        W: 1,
        R: 0,
        P: 2,
        BZ: 3,
        BS: 11,
        RB: -8,
        Pkt: 3,
    },
]
const GroupF = [
    {
        place: 1,
        src: "/images/morocco.png",
        name: "Morocco",
        GK:["	Yassine Bounou","Munir Mohamedi","Ahmed Reda Tagnaouti",],
        DF:["Achraf Hakimi","Noussair Mazraoui","Nayef Aguerd","Romain Saïss","Jawad El Yamiq","Achraf Dari","Badr Benoun","Yahia Attiyat Allah",],
        MF:["Sofyan Amrabat","Hakim Ziyech","Azzedine Ounahi","	Abdelhamid Sabiri","Ilias Chair","Selim Amallah","Bilal El Khannous","	Yahya Jabrane",],
        FW:["Abderrazak Hamdallah","Anass Zaroury","Zakaria Aboukhlal","Abde Ezzalzouli","	Sofiane Boufal","Youssef En-Nesyri","Walid Cheddira",],
        W: 2,
        R: 1,
        P: 0,
        BZ: 4,
        BS: 1,
        RB: 3,
        Pkt: 7,
    },
    {
        place: 2,
        src: "/images/croatia.png",
        name: "Croatia",
        GK:["	Dominik Livaković","Ivo Grbić","	Ivica Ivušić",],
        DF:["	Josip Stanišić","Borna Barišić","	Martin Erlić","	Dejan Lovren","	Borna Sosa","	Joško Gvardiol","	Domagoj Vida","	Josip Juranović","Josip Šutalo"],
        MF:["	Lovro Majer","Mateo Kovačić","Luka Modrić","Marcelo Brozović","Nikola Vlašić","Mario Pašalić","Luka Sučić","Kristijan Jakić",],
        FW:["Ivan Perišić","Andrej Kramarić","Marko Livaja","Bruno Petković","	Ante Budimir","Mislav Oršić",],
        W: 1,
        R: 2,
        P: 0,
        BZ: 4,
        BS: 1,
        RB: 3,
        Pkt: 5,
    },
    {
        place: 3,
        src: "/images/belgium.png",
        name: "Belgium",
        GK:["Thibaut Courtois","	Simon Mignolet","Koen Casteels",],
        DF:["Toby Alderweireld","	Arthur Theate","Wout Faes","Jan Vertonghen","Thomas Meunier","Timothy Castagne","Zeno Debast",],
        MF:["Axel Witsel","Kevin De Bruyne","Youri Tielemans","Yannick Carrasco","Amadou Onana","	Leander Dendoncker","Hans Vanaken","Charles De Ketelaere",],
        FW:["	Romelu Lukaku","Dries Mertens","Thorgan Hazard","	Leandro Trossard","Michy Batshuayi","Loïs Openda","Jérémy Doku",],
        W: 1,
        R: 1,
        P: 1,
        BZ: 1,
        BS: 2,
        RB: -1,
        Pkt: 4,
    },
    {
        place: 4,
        src: "/images/canada.png",
        name: "Canada",
        GK:["Dayne St. Clair","James Pantemis","Milan Borjan",],
        DF:["Alistair Johnston","Sam Adekugbe","Kamal Miller","Steven Vitória","Richie Laryea","Derek Cornelius","Joel Waterman",],
        MF:["Samuel Piette","Stephen Eustáquio","Liam Fraser","Atiba Hutchinson","Mark-Anthony Kaye","Ismaël Koné","	Jonathan Osorio","David Wotherspoon",],
        FW:["Lucas Cavallini","Junior Hoilett","	Tajon Buchanan","Iké Ugbo","	Cyle Larin","Alphonso Davies","	Jonathan David","	Liam Millar",],
        W: 0,
        R: 0,
        P: 3,
        BZ: 2,
        BS: 7,
        RB: -5,
        Pkt: 0,
    },
    
]
const GroupG = [
    {
        place: 1,
        src: "/images/brazil.png",
        name: "Brazil",
        GK:["Alisson","	Weverton","Ederson",],
        DF:["Danilo","Thiago Silva","	Marquinhos","Alex Sandro","	Dani Alves","	Éder Militão","Alex Telles","	Bremer",],
        MF:["Casemiro","Lucas Paquetá","Fred","Raphinha","Fabinho","Bruno Guimarães","Éverton Ribeiro",],
        FW:["Richarlison","Neymar","Gabriel Jesus","Antony","Vinícius Júnior","Rodrygo","Pedro","Gabriel Martinelli"],
        W: 2,
        R: 0,
        P: 1,
        BZ: 3,
        BS: 1,
        RB: 2,
        Pkt: 6,
    },
    {
        place: 2,
        src: "/images/switzerland.png",
        name: "Switzerland",
        GK:["Yann Sommer","Jonas Omlin","Gregor Kobel","Philipp Köhn"],
        DF:["	Silvan Widmer","	Nico Elvedi","	Manuel Akanji","Ricardo Rodriguez","	Eray Cömert","Fabian Schär",],
        MF:["Edimilson Fernandes","Denis Zakaria","Remo Freuler","Granit Xhaka","Renato Steffen","Michel Aebischer","Djibril Sow","Fabian Frei","Xherdan Shaqiri","Fabian Rieder","Ardon Jashari",],
        FW:["	Breel Embolo","Haris Seferovic","Christian Fassnacht","Ruben Vargas","Noah Okafor",],
        W: 2,
        R: 0,
        P: 1,
        BZ: 4,
        BS: 3,
        RB: 1,
        Pkt: 6,
    },
    {
        place: 3,
        src: "/images/cameroon.png",
        name: "Cameroon",
        GK:["Simon Ngapandouetnbu","Devis Epassy","André Onana",],
        DF:["Nicolas Nkoulou","Christopher Wooh","Olivier Mbaizo","Collins Fai","Jean-Charles Castelletto","Enzo Ebosse","Nouhou Tolo",],
        MF:["Jerome Ngom Mbekeli","Gaël Ondoua","André-Frank Zambo Anguissa","Samuel Gouet","Pierre Kunde","Martin Hongla","Olivier Ntcham"],
        FW:["Moumi Ngamaleu","Georges-Kévin Nkoudou","Jean-Pierre Nsame","	Vincent Aboubakar","Christian Bassogog","	Karl Toko Ekambi","	Eric Maxim Choupo-Moting","Bryan Mbeumo","	Souaibou Marou"],
        W: 1,
        R: 1,
        P: 1,
        BZ: 4,
        BS: 4,
        RB: 0,
        Pkt: 4,
    },
    {
        place: 4,
        src: "/images/serbia.png",
        name: "Serbia",
        GK:["Marko Dmitrović","Predrag Rajković","	Vanja Milinković-Savić",],
        DF:["Strahinja Pavlović","Strahinja Eraković","Nikola Milenković","Miloš Veljković","	Stefan Mitrović","	Srđan Babić","Filip Mladenović",],
        MF:["	Nemanja Maksimović","Nemanja Radonjić","Nemanja Gudelj","Dušan Tadić","	Andrija Živković","Saša Lukić","	Filip Kostić","Uroš Račić","Sergej Milinković-Savić","Filip Đuričić","	Darko Lazović","Ivan Ilić","Marko Grujić",],
        FW:["Aleksandar Mitrović","	Luka Jović","	Dušan Vlahović"],
        W: 0,
        R: 1,
        P: 2,
        BZ: 5,
        BS: 8,
        RB: -3,
        Pkt: 1,
    },
]
const GroupH = [
    {
        place:1,
        src: "/images/portugal.png",
        name: "Portugal",
        GK:["	Rui Patrício","José Sá","Diogo Costa",],
        DF:["	Diogo Dalot","Pepe","	Rúben Dias","Raphaël Guerreiro","Danilo Pereira","	Nuno Mendes","	João Cancelo","António Silva",],
        MF:["João Palhinha","Bruno Fernandes","Bernardo Silva","William Carvalho","	Vitinha","João Mário","	Rúben Neves","Matheus Nunes","Otávio",],
        FW:["	Cristiano Ronaldo","André Silva","João Félix","Rafael Leão","	Ricardo Horta","	Gonçalo Ramos"],
        W: 2,
        R: 0,
        P: 1,
        BZ: 6,
        BS: 4,
        RB: 2,
        Pkt: 6,
    },
    {
        place: 2,
        src: "/images/south-korea.png",
        name: "South_Korea",
        GK:["	Kim Seung-gyu","	Song Bum-keun","Jo Hyeon-woo",],
        DF:["Yoon Jong-gyu","Kim Jin-su","	Kim Min-jae","	Hong Chul","	Kim Moon-hwan","	Kim Young-gwon","	Kwon Kyung-won","Kim Tae-hwan","Cho Yu-min"],
        MF:["Jung Woo-young","	Hwang In-beom","Son Heung-min","	Paik Seung-ho","Lee Jae-sung","Hwang Hee-chan","	Son Jun-ho","Na Sang-ho","Lee Kang-in","	Kwon Chang-hoon","Jeong Woo-yeong","Song Min-kyu",],
        FW:["	Cho Gue-sung","Hwang Ui-jo"],
        W: 1,
        R: 1,
        P: 1,
        BZ: 4,
        BS: 4,
        RB: 0,
        Pkt: 4,
    },
    {
        place: 3,
        src: "/images/uruguay.png",
        name: "Uruguay",
        GK:["Fernando Muslera","Sebastián Sosa","Sergio Rochet",],
        DF:["José Giménez","Diego Godín","Ronald Araújo","Guillermo Varela","Mathías Olivera","	Matías Viña","Sebastián Coates","	Martín Cáceres","	José Luis Rodríguez",],
        MF:["Matías Vecino","	Rodrigo Bentancur","Nicolás de la Cruz","Giorgian de Arrascaeta","Lucas Torreira","Federico Valverde","Manuel Ugarte",],
        FW:["Facundo Pellistri","Luis Suárez","Darwin Núñez","	Maxi Gómez","	Facundo Torres","Edinson Cavani","Agustín Canobbio",],
        W: 1,
        R: 1,
        P: 1,
        BZ: 2,
        BS: 2,
        RB: 0,
        Pkt: 4,
    },
    {
        place: 4,
        src: "/images/ghana.png",
        name: "Ghana",
        GK:["Lawrence Ati-Zigi","Ibrahim Danlad","	Abdul Manaf Nurudeen",],
        DF:["Tariq Lamptey","Denis Odoi","Mohammed Salisu","Gideon Mensah","Joseph Aidoo","Baba Rahman","Daniel Amartey","	Alexander Djiku","Alidu Seidu",],
        MF:["Thomas Partey","Elisha Owusu","Daniel-Kofi Kyereh","André Ayew","	Daniel Afriyie","Mohammed Kudus","	Salis Abdul Samed",],
        FW:["Abdul Fatawu Issahaku","	Jordan Ayew","Osman Bukari","	Iñaki Williams","Kamaldeen Sulemana","	Kamal Sowah","	Antoine Semenyo",],
        W: 1,
        R: 0,
        P: 2,
        BZ:5,
        BS: 7,
        RB: -2,
        Pkt: 3,
    },
]

const allGroups = [...GroupA, ...GroupB,...GroupC,...GroupD,...GroupE,...GroupF, ...GroupG, ...GroupH]
module.exports = {allGroups, GroupA,GroupB,GroupC,GroupD,GroupE,GroupF,GroupG,GroupH}

